services:
    db:
        image: mariadb
        container_name: trucks_db
        dns_search: trucks.local
        volumes:
            - "./mariadb/sql:/sql:delegated"
        restart: always
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_DATABASE: '${DB_NAME:-trucks_db}'
            MYSQL_USER: '${DB_USER:-trucks}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-trucks}'
        hostname: trucks-db
        ports:
            - '${DB_PORT:-3306}:3306'

    trucks-web:
        container_name: trucks_web
        cap_add:
            - SYS_PTRACE
        links:
            - db
            - redis
        dns_search: trucks.local
        command: /var/www/scripts/docker/start.sh
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            MYSQL_DATABASE: '${DB_NAME:-trucks}'
            MYSQL_USER: '${DB_USER:-trucks}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-trucks}'
        hostname: trucks-web
        ports:
            - 80:80
        volumes:
            - "./:/var/www:delegated"
        depends_on:
            - db
            - redis

    redis:
        container_name: trucks_redis
        image: "redis"
        hostname: redis
        ports:
            - "6379:6379"
networks:
    default:
